# Generated by Django 5.2.14 on 2026-05-27 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geografico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hs', models.CharField(max_length=10)),
                ('descripcion_partida', models.TextField(blank=True, null=True)),
                ('arancel_ad_valorem', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('arancel_especifico', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unidad_arancel_esp', models.CharField(blank=True, max_length=20, null=True)),
                ('iva_importacion', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('otros_impuestos', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('descripcion_otros', models.TextField(blank=True, null=True)),
                ('tiene_preferencia', models.BooleanField(default=False)),
                ('acuerdo_preferencia', models.CharField(blank=True, max_length=100, null=True)),
                ('arancel_preferencial', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('fecha_vigencia_desde', models.DateField()),
                ('fecha_vigencia_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fuente', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pais_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geografico.paisdestino')),
            ],
            options={
                'db_table': 'aranceles',
            },
        ),
        migrations.CreateModel(
            name='RegulacionFitosanitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hs', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion_producto', models.TextField(blank=True, null=True)),
                ('tipo_regulacion', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('organismo_emisor', models.CharField(blank=True, max_length=150, null=True)),
                ('organismo_receptor', models.CharField(blank=True, max_length=150, null=True)),
                ('documentos_requeridos', models.JSONField(blank=True, default=dict, null=True)),
                ('plazo_tramite_dias', models.IntegerField(blank=True, null=True)),
                ('costo_estimado_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vigencia_dias', models.IntegerField(blank=True, null=True)),
                ('fecha_vigencia_desde', models.DateField(blank=True, null=True)),
                ('fecha_vigencia_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pais_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geografico.paisdestino')),
            ],
            options={
                'db_table': 'regulaciones_fitosanitarias',
            },
        ),
        migrations.CreateModel(
            name='RequisitoEtiquetado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_hs_prefijo', models.CharField(blank=True, max_length=6, null=True)),
                ('idiomas_requeridos', models.JSONField(default=list)),
                ('campos_obligatorios', models.JSONField(default=dict)),
                ('requiere_tabla_nutricional', models.BooleanField(default=False)),
                ('sistema_nutricional', models.CharField(blank=True, max_length=30, null=True)),
                ('requiere_codigo_barras', models.BooleanField(default=False)),
                ('estandar_codigo_barras', models.CharField(blank=True, max_length=20, null=True)),
                ('requiere_registro_sanitario', models.BooleanField(default=False)),
                ('organismo_registro', models.CharField(blank=True, max_length=150, null=True)),
                ('requiere_fecha_vencimiento', models.BooleanField(default=True)),
                ('formato_fecha_vencimiento', models.CharField(blank=True, max_length=20, null=True)),
                ('instrucciones_conservacion', models.BooleanField(default=False)),
                ('advertencias_especiales', models.TextField(blank=True, null=True)),
                ('norma_vigente', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_vigencia_desde', models.DateField(blank=True, null=True)),
                ('fecha_vigencia_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pais_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geografico.paisdestino')),
            ],
            options={
                'db_table': 'requisitos_etiquetado',
            },
        ),
        migrations.CreateModel(
            name='RestriccionImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hs', models.CharField(blank=True, max_length=10, null=True)),
                ('producto_descripcion', models.TextField(blank=True, null=True)),
                ('tipo_restriccion', models.CharField(max_length=30)),
                ('descripcion_restriccion', models.TextField()),
                ('cantidad_cuota', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('unidad_cuota', models.CharField(blank=True, max_length=20, null=True)),
                ('autoridad_competente', models.CharField(blank=True, max_length=150, null=True)),
                ('base_legal', models.TextField(blank=True, null=True)),
                ('fecha_vigencia_desde', models.DateField()),
                ('fecha_vigencia_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pais_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geografico.paisdestino')),
            ],
            options={
                'db_table': 'restricciones_importacion',
            },
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_origen', models.CharField(max_length=3)),
                ('moneda_destino', models.CharField(max_length=3)),
                ('fecha', models.DateField()),
                ('tasa', models.DecimalField(decimal_places=8, max_digits=18)),
                ('fuente', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipos_cambio',
                'unique_together': {('moneda_origen', 'moneda_destino', 'fecha')},
            },
        ),
    ]
