# Generated by Django 5.2.14 on 2026-05-27 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribuidores', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaHistorica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('cantidad_unidades', models.IntegerField()),
                ('precio_unitario_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_venta_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('canal_venta', models.CharField(default='Mayorista', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='distribuidores.distribuidor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Venta Histórica',
                'verbose_name_plural': 'Ventas Históricas',
                'db_table': 'comercial_venta_historica',
            },
        ),
    ]
