# Generated by Django 5.2.14 on 2026-05-27 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo_hs', models.CharField(max_length=10)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategoria', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('peso_unitario_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('volumen_unitario_m3', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('requiere_cert_origen', models.BooleanField(default=False)),
                ('requiere_cert_sanitario', models.BooleanField(default=False)),
                ('es_producto_controlado', models.BooleanField(default=False)),
                ('temperatura_conservacion', models.CharField(blank=True, max_length=30, null=True)),
                ('vida_util_dias', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='empresas.empresaexportadora')),
            ],
            options={
                'db_table': 'productos',
                'indexes': [models.Index(fields=['codigo_hs'], name='productos_codigo__20d7e3_idx'), models.Index(fields=['empresa'], name='productos_empresa_eb8cc4_idx')],
            },
        ),
    ]
