# Generated by Django 5.2.14 on 2026-05-27 14:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geografico', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('contacto_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('contacto_email', models.EmailField(blank=True, max_length=120, null=True)),
                ('contacto_telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('canal', models.CharField(choices=[('retail', 'Retail'), ('mayorista', 'Mayorista'), ('horeca', 'Horeca'), ('farmacia', 'Farmacia'), ('online', 'Online'), ('otro', 'Otro')], max_length=50)),
                ('capacidad_almacenamiento_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('api_usuario', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('api_hash_pwd', models.CharField(blank=True, max_length=128, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, null=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuidores', to='geografico.paisdestino')),
            ],
            options={
                'db_table': 'distribuidores',
            },
        ),
        migrations.CreateModel(
            name='SellOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('semana_iso', models.SmallIntegerField(blank=True, editable=False, null=True)),
                ('mes', models.SmallIntegerField(blank=True, editable=False, null=True)),
                ('anio', models.SmallIntegerField(blank=True, editable=False, null=True)),
                ('cantidad_vendida', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('precio_venta_local', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('moneda_local', models.CharField(blank=True, max_length=3, null=True)),
                ('precio_venta_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('stock_cierre', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('canal_venta', models.CharField(blank=True, max_length=50, null=True)),
                ('fuente_dato', models.CharField(default='api', max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribuidores.distribuidor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'db_table': 'sell_out',
            },
        ),
    ]
