# Generated by Django 5.2.14 on 2026-05-27 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribuidores', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyeccionDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_proyeccion', models.DateField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('cantidad_proyectada', models.DecimalField(decimal_places=4, max_digits=14)),
                ('limite_inferior_95', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('limite_superior_95', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('modelo_utilizado', models.CharField(choices=[('ARIMA', 'ARIMA'), ('Prophet', 'Prophet'), ('ensemble', 'Ensemble'), ('manual', 'Manual')], max_length=30)),
                ('version_modelo', models.CharField(blank=True, max_length=20, null=True)),
                ('mape_modelo', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('horizonte_semanas', models.SmallIntegerField(blank=True, null=True)),
                ('vigente', models.BooleanField(default=True)),
                ('distribuidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones', to='distribuidores.distribuidor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones', to='productos.producto')),
            ],
            options={
                'db_table': 'proyecciones_demanda',
                'unique_together': {('producto', 'distribuidor', 'fecha_proyeccion', 'version_modelo')},
            },
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('fecha_quiebre_estimado', models.DateField(blank=True, null=True)),
                ('stock_actual', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('stock_disponible_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('demanda_proyectada', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('nivel_criticidad', models.CharField(choices=[('verde', 'Verde'), ('amarillo', 'Amarillo'), ('rojo', 'Rojo')], max_length=10)),
                ('porcentaje_cobertura', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('en_gestion', 'En Gestión'), ('resuelta', 'Resuelta'), ('descartada', 'Descartada')], default='activa', max_length=20)),
                ('usuario_asignado', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('notas_resolucion', models.TextField(blank=True, null=True)),
                ('distribuidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_stock', to='distribuidores.distribuidor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_stock', to='productos.producto')),
                ('proyeccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='motor_ia.proyecciondemanda')),
            ],
            options={
                'db_table': 'alertas_stock',
            },
        ),
    ]
