# Generated by Django 5.2.14 on 2026-05-27 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribuidores', '0001_initial'),
        ('empresas', '0001_initial'),
        ('geografico', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_exportacion', models.CharField(blank=True, max_length=30, unique=True)),
                ('fecha_embarque', models.DateField()),
                ('fecha_llegada_estimada', models.DateField(blank=True, null=True)),
                ('fecha_llegada_real', models.DateField(blank=True, null=True)),
                ('incoterm', models.CharField(choices=[('EXW', 'EXW'), ('FCA', 'FCA'), ('FAS', 'FAS'), ('FOB', 'FOB'), ('CFR', 'CFR'), ('CIF', 'CIF'), ('CPT', 'CPT'), ('CIP', 'CIP'), ('DAP', 'DAP'), ('DPU', 'DPU'), ('DDP', 'DDP')], max_length=3)),
                ('via_transporte', models.CharField(choices=[('maritimo', 'Marítimo'), ('aereo', 'Aéreo'), ('terrestre', 'Terrestre'), ('multimodal', 'Multimodal')], max_length=20)),
                ('empresa_naviera', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_contenedor', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_bl', models.CharField(blank=True, max_length=50, null=True)),
                ('puerto_embarque', models.CharField(blank=True, max_length=100, null=True)),
                ('puerto_destino', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_fob_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('flete_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('seguro_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_cif_usd', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('en_aduana', 'En Aduana'), ('en_transito', 'En Tránsito'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada'), ('con_incidencia', 'Con Incidencia')], default='borrador', max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario_creacion', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('distribuidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exportaciones', to='distribuidores.distribuidor')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exportaciones', to='empresas.empresaexportadora')),
                ('pais_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exportaciones', to='geografico.paisdestino')),
            ],
            options={
                'db_table': 'exportaciones',
            },
        ),
        migrations.CreateModel(
            name='DocumentoAduanero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DUE', 'DUE'), ('BL', 'BL'), ('guia_aerea', 'Guía Aérea'), ('cert_origen', 'Cert. Origen'), ('cert_sanitario', 'Cert. Sanitario'), ('cert_fitosanitario', 'Cert. Fitosanitarios'), ('factura_comercial', 'Factura Comercial'), ('lista_empaque', 'Lista Empaque'), ('cert_analisis', 'Cert. Análisis'), ('permiso_importacion', 'Permiso Importación'), ('otro', 'Otro')], max_length=50)),
                ('numero_documento', models.CharField(blank=True, max_length=60, null=True)),
                ('entidad_emisora', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('archivo_url', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('emitido', 'Emitido'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('exportacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='operaciones_logisticas.exportacion')),
            ],
            options={
                'db_table': 'documentos_aduaneros',
            },
        ),
        migrations.CreateModel(
            name='ItemExportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_linea', models.SmallIntegerField()),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('precio_unitario_usd', models.DecimalField(decimal_places=4, max_digits=12)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal_usd', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True)),
                ('peso_total_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('exportacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operaciones_logisticas.exportacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_exportacion', to='productos.producto')),
            ],
            options={
                'db_table': 'items_exportacion',
                'unique_together': {('exportacion', 'numero_linea')},
            },
        ),
    ]
