# Generated by Django 5.2.14 on 2026-05-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaisDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_iso2', models.CharField(max_length=2, unique=True)),
                ('codigo_iso3', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_en', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=60, null=True)),
                ('moneda_codigo', models.CharField(blank=True, max_length=3, null=True)),
                ('moneda_nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('idioma_oficial', models.CharField(blank=True, max_length=60, null=True)),
                ('zona_horaria', models.CharField(blank=True, max_length=60, null=True)),
                ('acuerdo_comercial', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'paises_destino',
            },
        ),
    ]
