# Generated by Django 5.2.14 on 2026-05-27 14:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaExportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('razon_social', models.CharField(max_length=200)),
                ('ruc_nit', models.CharField(max_length=30, unique=True)),
                ('pais_origen', models.CharField(max_length=2)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('representante', models.CharField(blank=True, max_length=150, null=True)),
                ('cert_iso9001', models.BooleanField(default=False)),
                ('cert_bpm', models.BooleanField(default=False)),
                ('cert_haccp', models.BooleanField(default=False)),
                ('cert_otros', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'empresas_exportadoras',
            },
        ),
    ]
